### ISSUE TITLE
Resourant file should not be committed

### ISSUE THREAD

**Issue by lurenzsgp** [AlessandroSica/Lunch_Organizer_Bot#10]
Why have you committed to the restaurant list?

To create a more generic solution where a common structure of the CSV is shared and the file is loaded from a configurable path.

Following that idea each user can have and use its CSV file and let the app load it, without downloading the one you are providing. The one you are providing can be a good example for new adopters

**Comment by AlessandroSica** [comment]
Now if there isn't an additional file added the program works with the example file, and in the description there is written how to make your own one and where to put it. While the file that I am using is now ignore by git.
