### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by lurenzsgp** [AlessandroSica/Lunch_Organizer_Bot#8]
Hi, I would like to try the boat but the documentation is really generic.

Is possible to improve it and get a few examples of use?

**Comment by AlessandroSica** [comment]
I have upgraded the description of the project. Tell me what do you think about it. Is it better now?

**Comment by lurenzsgp** [comment]
Now is clear what the boat is doing but how can I run it on a new Slack workspace?

1. How can I start the server?
2. How to trigger the message?
3. Which is the format of the env file?

**Comment by AlessandroSica** [comment]
The description now has also a guide on how to activate the bot, and it includes all the steps needed to do including the .env file. The Raspberry pi documentation however is still missing.

**Comment by AlessandroSica** [comment]
Now also the documentation on how to activate and use the Raspberry Pi is done.
