### ISSUE TITLE
Can we remove link preview?

### ISSUE THREAD

**Issue by lurenzsgp** [AlessandroSica/Lunch_Organizer_Bot#9]
Link previews are really long and it's impossible to see the reaction to the message without scrolling.
![Screenshot 2022-06-28 at 12 16 23](https://user-images.githubusercontent.com/9417836/176155216-9527e422-4f1f-43b8-b3cd-37eeaf1c74c9.png)

**Comment by AlessandroSica** [comment]
Thank you for your suggestion. The expansion of the link is now removed.

**Comment by lurenzsgp** [comment]
How have you solved the issue? Nothing has been linked to the discussion
